### PR TITLE
Add Travis, Issue, and License badge to README

### PR DESCRIPTION
**Pull request by thepushkarp**
### Description

- Added Travis, Issue, and License badge to README in for-the-badge style.
- Also removed Code Style - semistandard badge as code style does not follows semistandard now. 

###  Screenshot Before Change:

iiitv_getmein-web_ Portal to get an invite to IIITV GitHub organization - Microsoft Edge 15-05-2019 02_07_54

### Screenshot After Change:

iiitv_getmein-web_ Portal to get an invite to IIITV GitHub organization - Microsoft Edge 15-05-2019 02_08_30

### Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Non Functional Requirement
- [x] Follows the code style of this project.
- [ ] Tests Cover Changes
- [x] I have performed a self-review of my own code
- [x] All new and existing tests passed.
- [x] Documentation

### CODE REVIEW

**Comment by anshumanv** [comment]
We can also put up an issue for the design team to create a repo logo 🤔

**Comment by aashutoshrathi** [comment]
@pranayag Can we get a logo?

**Comment by thepushkarp** [comment]
Screenshot_20190515-190307__01
@aashutoshrathi I have made the title centred and a few changes too. Is this alright?

**Comment by pranayag** [comment]
> @pranayag Can we get a logo?

Sure!

**Comment by aashutoshrathi** [comment]
@thepushkarp this looks great.
I think after we have a logo you can send another PR.

**Pull request merged**
