### PR TITLE
add target attribute to links

### LINKED ISSUE #126: Page doesn't open in new tab
## Expected Behavior
when we click on the social icons the page should open in a new tab
 It would be better if the page opens in a new tab

## Current Behavior and Triggers
  when we click on the social icons the page doesn't open in a new tab
  The user experience would be  better if the page opens in a new tab

## Possible Solution
 The above issue can be fixed by adding the target attribute ;
  adding target attribute fixes this issue

## Would you like to work on this issue?
Yes

### PR DESCRIPTION
**Pull request by RohithChittibommala**
Fixes #126 

### Description

- Added target attribute to links so that new page opens in new tab

### Types of changes
- [ ] New feature (non-breaking change which adds functionality)

### Non Functional Requirement
- [ ] Follows the code style of this project.
- [ ] Tests Cover Changes
- [ ] I have performed a self-review of my own code
- [ ] All new and existing tests passed.
- [ ] Documentation

### CODE REVIEW

**Comment by RohithChittibommala** [comment]
@aashutoshrathi  sir please review my pr

**Review by aashutoshrathi — CHANGES_REQUESTED** [review]
Please ensure that only changes are formatted the diff is kinda mixed as all content in file is changed

**Comment by RohithChittibommala** [comment]
@aashutoshrathi  sit can you please help me how to do that?

**Comment by yashshah2820** [comment]
> @aashutoshrathi sit can you please help me how to do that? I am getting the same result even if tried it again

Have you changed the whole ``index.html`` because it looks like it 🤔

**Comment by RohithChittibommala** [comment]
No sir I didn't do thatOn Sep 26, 2020 10:58 PM, Yash Shah <notifications@github.com> wrote:



@aashutoshrathi sit can you please help me how to do that? I am getting the same result even if tried it again



Have you changed the whole index.html because it looks like it 🤔

**Comment by aashutoshrathi** [comment]
@RohithChittibommala Turn off Prettier or similar linter in your editor and redo the changes. Let's close this one quick

**Pull request closed without merging**
