### PR TITLE
Add instruction in README under How to Use

### PR DESCRIPTION
**Pull request by thepushkarp**
### Description

Add instructions to join Gitter Channel, Member, Batch and Outsider Teams in IIITV Org and instructions to start contributing.

### Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Non Functional Requirement
- [ ] Follows the code style of this project.
- [ ] Tests Cover Changes
- [ ] I have performed a self-review of my own code
- [ ] All new and existing tests passed.
- [x] Documentation

### CODE REVIEW

**Comment by thepushkarp** [comment]
Taken from README in [IIITV getmein](https://github.com/iiitv/getmein).

@aashutoshrathi @rossoskull Should we also add Integrations for our newer repos to Gitter?
Currently, we have integrations from iiitv/aua, iiitv/getmein, iiitv/iiitv.github.com, iiitv/ShareIt on the General room.

**Comment by aashutoshrathi** [comment]
It will be good if we can mention that you get invited to Slack too.

**Comment by anshumanv** [comment]
* Let's limit README PRs to 2 for everyone so they push themselves to contribute code 
* Can we think of some amends of the team name `Outsiders` as the name doesn't sound too inclusive and thus may shut people off to contribute.

**Comment by thepushkarp** [comment]
I'm sorry for the Force Pushes😓. Messed up the Commit History a little.

**Pull request merged**
