### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by shivamtawari**
Corrected a typo and a grammatical mistake.

### CODE REVIEW

**Comment by thepushkarp** [comment]
Thanks!

**Comment by shivamtawari** [comment]
Hello! I have just started with open source contributions. I wanted to know that should I delete this branch now? Is it safe and a good practice? Or should I just keep it as it is?

**Comment by thepushkarp** [comment]
Sorry for the late reply.
It's okay to delete the branch after a merge. The changes have been reflected in the main repo. :smile:

**Comment by shivamtawari** [comment]
No worries and Thanks a lot 😊.

**Pull request merged**
