### PR TITLE
Small screen view with scroll feature 😄

### LINKED ISSUE #78: Footer containing links overlaps with body on small screens
## Expected Behavior

The footer containing the links should appear below the body. If there is less screen space, it should appear below after scrolling and not on top of it.

## Current Behavior

On small screens and in landscape mode, this overlapping happens.

Annotation 2019-05-16 023836

## Your Environment

On most mobile browsers in landscape mode or while typing.

## Would you like to work on this issue?

No

### PR DESCRIPTION
**Pull request by AmanRaj1608**
Fixes  #78    #81 

### Fixed footer containing links on landscape mode on small screen

With solution of #78 which was done in PR #80 .

Now added fix for #81 too.

### Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Non Functional Requirement
- [x] Follows the code style of this project.
- [x] Tests Cover Changes
- [x] I have performed a self-review of my own code
- [ ] All new and existing tests passed.
- [ ] Documentation

### CODE REVIEW

**Comment by AmanRaj1608** [comment]
@aashutoshrathi 
I was not able to connect with my old PR #80 so i created a new PR with fix.

image

**Comment by aashutoshrathi** [comment]
Also on iPhone 5/SE.
image

**Comment by AmanRaj1608** [comment]
Fixed padding 
image

Also Iphone 5/SE problem is resolved 
image

**Comment by AmanRaj1608** [comment]
@rossoskull 
**Is this okay ?**

image


**Code -** 
image

**I can align it totally left but then in it will look good in portrait mode but not good in landscape mode. What should i do? Should I still add ?**

**Comment by aashutoshrathi** [comment]
@rossoskull Import the code to glitch

**Pull request merged**
